GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/book

#### single book
GET http://localhost:3000/api/book/625fb4d285b686ea00ffb795
###
#### delete book
DELETE http://localhost:3000/api/book/625fb4d285b686ea00ffb795
###

POST http://localhost:3000/api/book
Content-Type: application/json

{
  "title": "Book 15",
  "year": 2015,
  "rating": 3
}

###

POST http://localhost:3000/api/author
Content-Type: application/json

{
  "name": "Jannet book3",
  "town": "Vilnius",
  "bookId": "625e6550f0309fcf5bcd6df6"
}
###

###

PATCH  http://localhost:3000/api/author/625e6f363682344933687559
Content-Type: application/json

{
  "newName": "James bk1"
}

###

GET http://localhost:3000/api/author
###

GET http://localhost:3000/api/book-authors
###

GET http://localhost:3000/api/book-agg2